### PR TITLE
Fix some cornor cases

### LINKED ISSUE #15: COUNT command has no output
If you do `SELECT COUNT(*) FROM table1` you get `count(*)` as an output.
I think it's the title of a table... It's trying to create a table because the condition of the if is if has the SELECT keyword.
This was just an ugly hack to make things work fast and I didn't think on this case. This "parsing" has to be more sophisticated.

### PR DESCRIPTION
**Pull request by wangfenjin**
- Fix #15 
- Support `show databases` and `desc table` command
- Handle db related error

Two things I notice:
1. soci seems don't support sqlite dot command such as `.database`
2. plain_table seems not used? should we delete it?

### CODE REVIEW

**Comment by wangfenjin** [comment]
Hi @marimeireles , I think it's ready for review

Windows build failed is expected

**Comment by SylvainCorlay** [comment]
Thanks! Indeed the windows failure is expected.

**Comment by marimeireles** [comment]
Awesome @wangfenjin ! :D
I'm going to review it right now.

**Comment by wangfenjin** [comment]
I had create an issue  #21 for sqlite dot commands, we can address this issue later

**Comment by marimeireles** [comment]
Wow, I love it :)
Thank you so much for your contribution, it's super! :)

**Comment by marimeireles** [comment]
Ah, yeah, I forgot to address this:

> plain_table seems not used? should we delete it?

No, this was suppose to generate an output for `jupyter console`, so it's used here:

```
        pub_data["text/plain"] = plain_table.str();
```

But I just checked and it's broken. This is a known issue for a while now, will open an issue so I don't forget about it again.

**Pull request merged**
