### PR TITLE
support some sqlite dot commands

### PR DESCRIPTION
**Pull request by wangfenjin**
These are the most related commands we may use: `.databases, .tables, .schema, .indexes`

Address #21 , we should leave this issue open in case we need add other commands

### CODE REVIEW

**Comment by marimeireles** [comment]
Will revise it tomorrow, thanks & cheers! =)

**Comment by jankatins** [comment]
This will open a can of worms: e.g. postgresql (psql cli client) also has a lot of meta commands:https://www.postgresql.org/docs/9.2/app-psql.html#APP-PSQL-META-COMMANDS ...

**Comment by marimeireles** [comment]
hey @jankatins, thank you for the input.
You see any issues with starting to support this? I think the more the merrier, no? We won't have support to everything but it's a nice start.

**Comment by wangfenjin** [comment]
We could choose to support some commands that's necessary for use in jupyter but doesn't straightforward support by the db, such as in this case .databases and .tables, you even don't know how to use SQL to get that info.

If the DB backend support SQL like `show databases` or `show tables` we may choose not to implement that as everyone should know these SQL grammar

**Comment by jankatins** [comment]
Ok, maybe "can of worms" was a bit too negative. :-) 

The main issue I see is that adding these things will set some expectations ("that kernel supports the same features as the respective command line client") and I think it will bite in the long run: 
a) Because it's also maintenance cost in the long run.
b) If you support any, some users will be confused if some parts are not supported and you get swamped by these bugreports (e.g. postgresql has stuff to import CSV into a table (`\COPY`), and the CSV is where psql is run. You cannot rebuild that easily via the normal SQL `COPY` as that is run on the server and so has no access to the local filesystem).

**Pull request closed without merging**
