### PR TITLE
support vega-lite specs

### LINKED ISSUE #17: About vega plot command
Hi team,

I like this project, especially the idea integrate vega into the kernel. 

The command is `%XVEGA_PLOT X_FIELD EmployeeId GRID false Y_FIELD ReportsTo MARK area COLOR pink WIDTH 200 HEIGHT 200 <> SELECT EmployeeId, ReportsTo FROM employees` like this I think it's two complated, we need to write a lot of code to parse the user input and user need to learn new syntax.

So I suggest we follow the style I implement in [here](https://github.com/wangfenjin/xeus-tidb/blob/develop/examples/TiDB.ipynb):

```sql
%VEGA-LITE specs/arc_pie.vl.json 
SELECT 
    g.Name as category, 
    SUM(il.Quantity) as b, 
    ROUND((CAST(SUM(il.Quantity) as float) / (SELECT 
        SUM(Quantity) total
    FROM Chinook.InvoiceLine il
    INNER JOIN Chinook.Invoice i ON i.InvoiceId = il.InvoiceId
    WHERE i.BillingCountry = 'USA')) * 100, 2) value 
FROM Chinook.InvoiceLine il
INNER JOIN Chinook.Invoice i ON i.InvoiceId = il.InvoiceId 
INNER JOIN Chinook.Track t ON il.TrackId = t.TrackId 
INNER JOIN Chinook.Genre g ON t.GenreId = g.GenreId 
WHERE i.BillingCountry = 'USA' 
GROUP BY 1 
ORDER BY 2 DESC
LIMIT 10
```

This is a project I fork from this repo to verify my ideas and used to participants a hackathon, but I would like to contribute back and archive my repo.

And if we want to support define specs on the fly, and can add some command like:

```sql
%VEGA-LITE SET my_spec.vl.json
{
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {"timeUnit": "month", "field": "date", "type": "ordinal"},
    "y": {"aggregate": "mean", "field": "precipitation"}
  }
}

%VEGA-LITE PLOT my_spec.vl.json
select ...
```

What do you think?

### PR DESCRIPTION
**Pull request by wangfenjin**
I think after support json spec, we can delete the %XVEGA_PLOT command, and we don't need the parsers. Maybe we can decouple from xv_bindings, as what left is some helper functions in there.

Close #17

### CODE REVIEW

**Comment by wangfenjin** [comment]
@marimeireles Please help review code

**Comment by marimeireles** [comment]
Thank you for the PRs @wangfenjin, I'll look into them later today :)

**Comment by SylvainCorlay** [comment]
Hey @wangfenjin this is great work!

I don't think we should delete the xvega bindings though. Let's keep it around as there are some more possibilities with that being worked on.

**Comment by wangfenjin** [comment]
Hi @marimeireles , have you got time to review the code?

**Comment by marimeireles** [comment]
Hey @wangfenjin, sorry I was focusing on a different project, but I need a break from it, so I'm gonna look at it now. Sorry to keep you waiting and thanks again for the amazing work :)

**Comment by marimeireles** [comment]
Awesome work @wangfenjin, I'll merge once everything is green.
I'm writing a blog post to release `xeus-sql` to the world. I'd like to credit you for your contributions, please let me know if you're okay with that and if you'd like me to put your Github or twitter as link in the text so people can reach you if they want to :)
Once again, thanks for all the contributions!

**Comment by wangfenjin** [comment]
@marimeireles That’s very kind of you! You can link my GitHub, I don’t use Twitter too often. Thank you.

**Comment by wangfenjin** [comment]
@marimeireles I started to know xeus projects because your xeus-sqlite blogs, and then I write a similar xeus-clickhouse. Then I find this project and it’ll be amazing if we can support all sql db.

Looking forward to your new blog!

**Comment by wangfenjin** [comment]
And I'd like to translate a Chinese version of your blog to share to the Chinese community.

**Comment by marimeireles** [comment]
@wangfenjin that's awesome :)!
Thank you so much for offering this. It'd be crazy cool!

Just to keep you inside the loop: I was talking to @SylvainCorlay about this and he's part of the Jupyter's committee, so he's asking people there if it's okay to include languages other than English inside the Jupyter Blog (for now it's a purely English blog). I'd like to know if you're interested in posting your blog in there? Of course you're still free to post it anywhere else you want =) 

And also I'm curious to know if you'd like to write new content in Chinese for the Jupyter Blog related to use of SQL in Jupyter Notebooks (in case they agree in having new languages).

Thank you so much for your contributions, people like you makes me extra :heart: open source.

**Comment by wangfenjin** [comment]
@marimeireles Yes I'd like to contribute to the blog, in some cases blog is more important than just writing code :)

**Comment by marimeireles** [comment]
Awesome, I'll keep you posted about the news then =)

**Pull request merged**
